defmodule Beabadooble.Constants do
  def songs() do
    [
    "Take a Bite",
    "California",
    "One Time",
    "Real Man",
    "Tie My Shoes",
    "Girl Song",
    "Coming Home",
    "Ever Seen",
    "A Cruel Affair",
    "Post",
    "Beaches",
    "Everything I want",
    "The Man Who Left Too Soon",
    "This Is How It Went",
    "A Night To Remember",
    "the way things go",
    "Glue Song",
    "Beatopia Cultsong",
    "10:36",
    "Sunny day",
    "See you Soon",
    "Ripples",
    "the perfect pair",
    "broken cd",
    "Talk",
    "Lovesong",
    "Pictures of Us",
    "fairy song",
    "Don't get the deal",
    "tinkerbell is overrated",
    "You're here that's the thing",
    "Last Day On Earth",
    "Cologne",
    "Animal Noises",
    "He Gets Me So High",
    "Winter Wonderland",
    "Care",
    "Worth It",
    "Dye It Red",
    "Back To Mars",
    "Charlie Brown",
    "Emo Song",
    "Sorry",
    "Further Away",
    "Horen Sarrison",
    "How Was Your Day?",
    "Together",
    "Yoshimi, Forest, Magalene",
    "Are You Sure",
    "I Wish I Was Stephen Malkmus",
    "Sun More Often",
    "She Plays Bass",
    "Space Cadet",
    "Disappear",
    "1999",
    "Apple Cider",
    "Ceilings",
    "Angel",
    "You Lie All The Time",
    "Soren",
    "Everest",
    "Tired",
    "Dance with Me",
    "Art Class",
    "If You Want To",
    "Eighteen",
    "The Way I Spoke",
    "Susie May",
    "Home Alone",
    "Bobby",
    "Spacing Out",
    "Angry Song",
    "Coffee"
    ]
  end
end
